######################################################################
# Automatically generated by qmake (2.01a) Mon Apr 16 13:41:35 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += nodes.h window.h \
    mapND.h
SOURCES += main.cpp nodes.cpp window.cpp \
    mapND.cpp
